// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MvvmCross.Platforms.Ios.Views;
using MvvmcrossIosApp.Core.ViewModels;
using UIKit;

namespace MvvmcrossIosApp.iOS.UI
{
	public partial class Okviewcontroller : MvxViewController<ActionViewModel>
	{
		public Okviewcontroller (IntPtr handle) : base (handle)
		{
		}
	}
}
